server:
    port:
        9092

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring_boot
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MYSQL8Dialect
